function dataset = mpedata
    dataset = {...
        %struct('name', 'Scarlatti K.14', 'path', './data/Scarlatti_K14.m4a', 'begin', 0.2, 'end', 20, 'ymax', 1000, 'ymin', 60)...
        %struct('name', 'Fandango', 'path', './data/Fandango_Rodrigo.m4a', 'begin', 0, 'end', 8, 'ymax', 800, 'ymin', 60)...
        %struct('name', 'Beethoven Piano Sonata', 'path', './data/PianoSonataNo27_Beethoven.m4a', 'begin', 0, 'end', 9, 'ymax', 1000, 'ymin', 45)...
        %struct('name', 'Os Justi', 'path', './data/OsJusti_Bruckner.m4a', 'begin', 0.2, 'end', 20, 'ymax', 800, 'ymin', 80)...
        %struct('name', 'NHS-50', 'path', './data/NHSDiscography-050.mp3', 'begin', 6.5, 'end', 14.1, 'ymax', 1500, 'ymin', 80)...
        %struct('name', 'NHS-92', 'path', './data/NHSDiscography-092.mp3', 'begin', 2.5, 'end', 14.5, 'ymax', 1500, 'ymin', 80)...
        struct('name', 'Hirado-bushi', 'path', './data/Oiwake_b2.mp3', 'begin', 15, 'end', 28, 'ymax', 1500, 'ymin', 80)...
        %struct('name', 'FairEllendar', 'path', './data/FairEllender.m4a', 'begin', 0, 'end', 18, 'ymax', 1500, 'ymin', 80)...
        %struct('name', 'Sado-Okesa', 'path', './data/ç≤ìnÇ®ÇØÇ≥_ëIçzèÍÇ®ÇØÇ≥.wav', 'begin', 19, 'end', 39, 'ymax', 1500, 'ymin', 80)...
        %struct('name', 'AmaSua', 'path', './data/AmaSua.m4a', 'begin', 0, 'end', 18, 'ymax', 3000, 'ymin', 80)...
        %struct('name', 'CantoMet_Consensus20', 'path', './data/CantoMetConsensus_20.mp3', 'begin', 2.5, 'end', 15.5, 'ymax', 4000, 'ymin', 80)...
        %struct('name', 'CantoMet_Consensus17', 'path', './data/CantoMetConsensus_17.mp3', 'begin', 9.0, 'end', 20.0, 'ymax', 1500, 'ymin', 80)...
        %struct('name', 'CantoMet_Consensus02', 'path', './data/CantoMetConsensus_02.mp3', 'begin', 7.5, 'end', 23.5, 'ymax', 1500, 'ymin', 80)...
        };
end